name: vip
description: A Filmxy Mobile App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  flutter_screen_wake: ^1.0.2
  flutter_screenutil: ^5.2.0
  video_player: ^2.4.7
  http: ^0.13.4
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.8
  get: ^4.6.5
  status_bar_control: ^3.2.1
  shared_preferences: 2.0.15
  carousel_slider: ^4.1.1
  permission_handler: ^10.0.0
  flutter_svg: ^1.1.6
  readmore: ^2.2.0
  timeago:
    git:
      url: https://github.com/NOU-VANNET/timeago.git
      ref: main
  flutter_downloader: ^1.10.4
  percent_indicator: ^4.2.2
  external_path: ^1.0.1
  scroll_to_index: ^3.0.1
  video_thumbnail: ^0.5.3
  file_picker: ^5.2.9
  audioplayers: ^4.1.0
  url_launcher: ^6.1.11
  audio_video_progress_bar: ^0.10.0
  youtube_explode_dart: ^1.12.4
  device_info_plus: ^9.0.2
  package_info_plus: ^4.1.0
  package_rename: ^1.5.0
  google_sign_in: ^6.1.4
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.15
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "ic_launcher"
  ios: "assets/icons/ios_vip_logo.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/icons/android_vip_logo.png"
  image_path: "assets/icons/android_vip_logo.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#212121"
  image: "assets/icons/splash.png"
  image_dark: "assets/icons/splash.png"

package_rename_config:
  android:
    app_name: Monkey Player
    package_name: cc.playerapi.monkey_player
    lang: java

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/files/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
